apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |-
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8080
        traffic_direction: OUTBOUND
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              generate_request_id: true
              tracing: {}
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: hello
              http_filters:
              - name: envoy.filters.http.router
                typed_config: {}
              use_remote_address: true
      clusters:
      - name: hello
        connect_timeout: 0.250s
        type: static
        lb_policy: round_robin
        load_assignment:
          cluster_name: hello
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8000
      # Configure this cluster with the address of the datadog agent
      # for sending traces.
      - name: datadog_agent
        connect_timeout: 1s
        type: strict_dns
        lb_policy: round_robin
        load_assignment:
          cluster_name: datadog_agent
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: datadog-agent-tracer
                    port_value: 8126

    tracing:
      http:
        name: envoy.tracers.datadog
        typed_config:
          "@type": type.googleapis.com/envoy.config.trace.v3.DatadogConfig
          collector_cluster: datadog_agent   # matched against the named cluster
          service_name: my-web-app           # user-defined service name

    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
