apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: hello:0.1
          ports:
            - containerPort: 8000
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
        - name: envoy
          image: envoyproxy/envoy:v1.14.1
          command:
            - "envoy"
            - "-c"
            - "/etc/config/envoy.yaml"
          volumeMounts:
            - name: envoy-config-volume
              mountPath: /etc/config
          ports:
            - containerPort: 8080
            - containerPort: 9901
      volumes:
        - name: envoy-config-volume
          configMap:
            name: envoy-config
